name: 'Release-aware server Docker image create & push'

on:
  push:
    branches: [ master, helm-charts ]
    paths:
    - 'server/*'
    - '.github/workflows/*'
  pull_request:
    branches: [ master ]
    paths:
    - 'server/*'
    - '.github/workflows/*'
jobs:

  build-server-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd ./server
        docker build . --file Dockerfile --tag sdpequinor/release-aware-api:latest
        echo ${{ secrets.DOCKERHUB_PAT }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push sdpequinor/release-aware-api:latest
        docker logout
